
## Input and output options ##
fasta_path: "path/to/assembly.fasta"
gff_path: "path/to/assembly.gff"
output_path: "path/to/output_directory/" # directory to save results to
taxon_id: "<NCBI taxon ID>" # NCBI Taxon ID of query species

## Coverage options ##
include_coverage: "FALSE"
compute_coverage: "FALSE"
pbc_paths: ["paths/to/pbc.txt"]
bam: "path/to/bam"
reads: ["paths/to/read_files"]
insert_size: "200" # insert size for paired end reads

## Taxonomic assignment options ##
compute_tax_assignment: "TRUE"
extract_proteins: "TRUE"       # set proteins_path as output path
proteins_path: "path/to/proteins.fasta"
tax_assignment_path: "path/to/taxonomic_hits.txt"
database_path: "path/to/database.dmnd" #
taxon_exclude: "TRUE"
assignment_mode: "exhaustive"

## Plot output options ##
update_plots: "FALSE"
num_groups_plot: "25"
merging_labels: ["strain"]
output_pdf: "TRUE"
output_png: "FALSE"

## Gene info options ##
include_pseudogenes: "FALSE"

## PCA options ##
input_variables: "c_name,c_num_of_genes,c_len,c_genelenm,c_genelensd,g_len,g_lendev_c,g_abspos,g_terminal,c_cov,c_covsd,g_cov,g_covsd,g_covdev_c,c_pearson_r,g_pearson_r_o,g_pearson_r_c"
perform_parallel_analysis: "FALSE"
num_pcs: "3"
coverage_cutoff_mode: "default"

## Clustering options ##
perform_kmeans: "FALSE"
kmeans_k: "default"
perform_hclust: "FALSE"
hclust_k: "default"
perform_mclust: "FALSE"
mclust_k: "default"
perform_dbscan: "FALSE"
dbscan_groups: "default"
custom_eps: "0.3"
custom_minPts: "10"
