
## Input and output options ##
fasta_path: "./example/test.fasta"
gff_path: "./example/test.gff"
output_path: "./MILTS_report/" # directory to save results to
taxon_id: "107806" # NCBI Taxon ID of you query species

## Coverage options ##
include_coverage: "TRUE"
compute_coverage: "FALSE"
pbc_paths: ["./example/test.pbc.txt","./example/test.pbc_2.txt"]
bam: "path/to/mapping.bam"
reads: "path/to/reads"
insert_size: ""

## Gene info options ##
include_pseudogenes: "FALSE"

## Taxonomic assignment options ##
compute_tax_assignment: "FALSE"
extract_proteins: "FALSE"       # set proteins_path as output path
proteins_path: "./example/test_proteins.fasta"
tax_assignment_path: "./example/top10_hits.txt"
nr_db_path: "path/to/nrTaxonomy.dmnd"
taxon_exclude: "TRUE"
assignment_mode: "quick"
quick_mode_search_rank: "phylum"
quick_mode_match_rank: "class"

## Plot output options ##
update_plots: "TRUE"
num_groups_plot: "25"
merging_labels: ["strain"]
output_pdf: "TRUE"
output_png: "FALSE"

## PCA options ##
input_variables: "c_name,c_num_of_genes,c_len,c_genelenm,c_genelensd,g_len,g_lendev_c,g_abspos,g_terminal,c_cov,c_covsd,g_cov,g_covsd,g_covdev_c,c_pearson_r,g_pearson_r_o,g_pearson_r_c"
perform_parallel_analysis: "FALSE"
num_pcs: "3"
coverage_cutoff_mode: "default"

## Clustering options ##
perform_kmeans: "TRUE"
kmeans_k: "default"
perform_hclust: "TRUE"
hclust_k: "default"
perform_mclust: "TRUE"
mclust_k: "default"
perform_dbscan: "TRUE"
dbscan_groups: "default"
custom_eps: "0.3"
custom_minPts: "10"
